no_cuda: False
gpu_ids:  "0,1,2,3,4,5,6,7"

do_train: True

crop_size: 768
batch_size: 2
model_input_size: 768

train_csv_path: ./data/train_patches.csv
val_csv_path: ./data/val_patches.csv
patches_root: ./data/patches

save_model_path: ./ckpt/pagin


basemodel_type: efficientnet
basemodel: EfficientNetB0

train_class_list:


train_patch_class_mapping:
  bfn: 
  - BFN
  aus: 
  - AUS
  ptc: 
  - PTC
  - SUS_PTC
  mtc: 
  - MTC
  fn: 
  - FN
  - MFOLL
  ss: 
  - SS
  - HURTHLE
  others: 
  - NON
  - RED
  - TS
  - NY
  - COLL
  - TC
  - NB
  - NORMAL
  - LN
  - FNeg
  - MGC

train_patch_class_list: 
- others
- bfn
- aus
- ptc
- mtc
- fn
- ss

upsample:
  BFN: 1
  PTC: 1
sample_weight: {}
select_n_others: 15
instances_per_image: 1

LR: 0.00001
optimizer: 'sgd' 
optim_args: {}
scheduler: CosineDecayRestarts
scheduler_args:  
  first_decay_steps: 1000 
  t_mul: 2.0 
  m_mul: 1.0
  alpha: 0.0